### ISSUE TITLE
using processing for 3D image mapping

### ISSUE THREAD

**Issue by mkeyno** [PimentNoir/processing-sketches#1]
hi
first of all I'm so sorry to open ticket for my question but I thought may I could have your guide to my 3D image issue , and I really appreciated if you could direct me to correct links or track
actually I'm Arduino Neopixel fan and tried to run the spherical POV. For run POV, each image should be converted to the number of lines which is used in each revolution , I think convert the planner POV must not be so hard for java base processing to pixelizid into lines but I don't now how to map an image on spherical and then converted to image lines
thanks again

**Comment by jerome-benoit** [comment]
Hello,  
I do not fully understand what you're trying to achieve. But you can map spherical coordinates to cartesian ones very easily : https://en.wikipedia.org/wiki/Spherical_coordinate_system. 

And if you want to map a spherical image representation to a planar one, you can use a map projection - well one of them might fit your needs - and a stereographic projection to do the reverse : https://en.wikipedia.org/wiki/Stereographic_projection.
